services:
  - type: web
    name: foodapp-backend
    env: python
    region: oregon   # or closest to your users
    plan: free       # or starter, standard, etc.
    branch: main
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn payment.wsgi:application --preload --workers=4 --threads=2 --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "foodapp-backend.onrender.com"
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: foodapp-db
          property: connectionString
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false

databases:
  - name: foodapp-db
    plan: free
    region: oregon
